swagger: "2.0"
info: {}
basePath: /restaurante/v1
paths: {}
definitions:
  interface{}:
    title: interface{}
    type: object
  models.ApiResponse:
    title: ApiResponse
    type: object
    properties:
      cause:
        type: string
      code:
        type: integer
        format: int64
      data:
        $ref: '#/definitions/models.any'
      message:
        type: string
  models.Cliente:
    title: Cliente
    type: object
    properties:
      APELLIDO:
        type: string
      DIRECCION:
        type: string
      NOMBRE:
        type: string
      OBSERVACIONES:
        type: string
      PASSWORD:
        type: string
      PK_DOCUMENTO_CLIENTE:
        type: integer
        format: int64
      TELEFONO:
        type: string
  models.Domicilio:
    title: Domicilio
    type: object
    properties:
      CREATED_AT:
        type: string
        format: datetime
      CREATED_BY:
        type: string
      DIRECCION:
        type: string
      ENTREGADO:
        type: boolean
      ESTADO_PAGO:
        type: string
      FECHA:
        type: string
        format: datetime
      OBSERVACIONES:
        type: string
      PK_ID_DOMICILIO:
        type: integer
        format: int64
      TELEFONO:
        type: string
      UPDATED_AT:
        type: string
        format: datetime
      UPDATED_BY:
        type: string
  models.LoginRequest:
    title: LoginRequest
    type: object
    properties:
      documento:
        type: integer
        format: int64
      password:
        type: string
  models.MetodoPago:
    title: MetodoPago
    type: object
    properties:
      DETALLE:
        type: string
      PK_ID_METODO_PAGO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
      TIPO:
        type: string
  models.Nomina:
    title: Nomina
    type: object
    properties:
      ESTADO_NOMINA:
        type: string
      FECHA:
        type: string
        format: datetime
      MONTO:
        type: integer
        format: int64
      PK_ID_NOMINA:
        type: integer
        format: int64
  models.Pago:
    title: Pago
    type: object
    properties:
      ESTADO_PAGO:
        type: string
      FECHA:
        type: string
      HORA:
        type: string
      MONTO:
        type: integer
        format: int64
      PK_ID_METODO_PAGO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
      UPDATED_AT:
        type: string
      UPDATED_BY:
        type: string
  models.Pedido:
    title: Pedido
    type: object
    properties:
      DELIVERY:
        type: boolean
      ESTADO_PEDIDO:
        type: string
      FECHA:
        type: string
      HORA:
        type: string
      PK_ID_DOMICILIO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
      PK_ID_PEDIDO:
        type: integer
        format: int64
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
      UPDATED_AT:
        type: string
      UPDATED_BY:
        type: string
  models.PedidoCliente:
    title: PedidoCliente
    type: object
    properties:
      PK_DOCUMENTO_CLIENTE:
        type: integer
        format: int64
      PK_ID_PEDIDO:
        type: integer
        format: int64
      PK_ID_PEDIDO_CLIENTE:
        type: integer
        format: int64
  models.Producto:
    title: Producto
    type: object
    properties:
      CALORIAS:
        type: integer
        format: int64
      CANTIDAD:
        type: integer
        format: int64
      DESCRIPCION:
        type: string
      ESTADO_PRODUCTO:
        type: string
      IMAGEN:
        type: string
      NOMBRE:
        type: string
      PK_ID_PRODUCTO:
        type: integer
        format: int64
      PRECIO:
        type: integer
        format: int64
  models.Reserva:
    title: Reserva
    type: object
    properties:
      CREATED_AT:
        type: string
        format: datetime
      CREATED_BY:
        type: string
      ESTADO_RESERVA:
        type: string
      FECHA:
        type: string
        format: datetime
      HORA:
        type: string
      INDICACIONES:
        type: string
      PERSONAS:
        type: integer
        format: int64
      PK_ID_RESERVA:
        type: integer
        format: int64
      UPDATED_AT:
        type: string
        format: datetime
      UPDATED_BY:
        type: string
  models.Restaurante:
    title: Restaurante
    type: object
    properties:
      PK_ID_CAMBIO_HORARIO:
        type: integer
        format: int64
      PK_ID_RESERVA:
        description: 'TODO: ESTÁ AL REVÉS'
        type: integer
        format: int64
      dias_laborales:
        type: string
      hora_apertura:
        type: string
      nombre_restaurante:
        type: string
      pk_id_restaurante:
        type: integer
        format: int64
  models.Trabajador:
    title: Trabajador
    type: object
    properties:
      APELLIDO:
        type: string
      FECHA_INGRESO:
        type: string
        format: datetime
      FECHA_NACIMIENTO:
        type: string
        format: datetime
      FECHA_RETIRO:
        type: string
        format: datetime
      HORARIO:
        type: string
      NOMBRE:
        type: string
      NUEVO:
        type: boolean
      PASSWORD:
        type: string
      PK_DOCUMENTO_TRABAJADOR:
        type: integer
        format: int64
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
      ROL:
        type: string
      SUELDO:
        type: integer
        format: int64
      TELEFONO:
        type: string
  models.any:
    title: any
    type: object
  nil:
    title: nil
    type: object
