swagger: "2.0"
info: {}
basePath: /restaurante/v1
paths: {}
definitions:
  models.Cliente:
    title: Cliente
    type: object
    properties:
      APELLIDO:
        type: string
      DIRECCION:
        type: string
      NOMBRE:
        type: string
      OBSERVACIONES:
        type: string
      PASSWORD:
        type: string
      PK_DOCUMENTO_CLIENTE:
        type: integer
        format: int64
      TELEFONO:
        type: string
  models.Restaurante:
    title: Restaurante
    type: object
    properties:
      DIAS_LABORALES:
        type: string
      HORA_APERTURA:
        type: string
      NOMBRE_RESTAURANTE:
        type: string
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
  nil:
    title: nil
    type: object
