swagger: "2.0"
info: {}
paths: {}
definitions:
  models.Cliente:
    title: Cliente
    type: object
    properties:
      APELLIDO:
        description: Apellido
        type: string
      DIRECCION:
        description: Dirección
        type: string
      NOMBRE:
        description: Nombre
        type: string
      OBSERVACIONES:
        description: Observaciones
        type: string
      PASSWORD:
        description: Contraseña
        type: string
      PK_DOCUMENTO_CLIENTE:
        description: Clave primaria
        type: integer
        format: int64
      TELEFONO:
        description: Teléfono
        type: string
  nil:
    title: nil
    type: object
