swagger: "2.0"
info: {}
basePath: /restaurante/v1
paths: {}
definitions:
  models.ApiResponse:
    title: ApiResponse
    type: object
    properties:
      cause:
        type: string
      code:
        type: integer
        format: int64
      data:
        $ref: '#/definitions/models.any'
      message:
        type: string
  models.Cliente:
    title: Cliente
    type: object
    properties:
      APELLIDO:
        type: string
      DIRECCION:
        type: string
      NOMBRE:
        type: string
      OBSERVACIONES:
        type: string
      PK_DOCUMENTO_CLIENTE:
        type: integer
        format: int64
      TELEFONO:
        type: string
  models.Domicilio:
    title: Domicilio
    type: object
    properties:
      DIRECCION:
        type: string
      ENTREGADO:
        type: boolean
      ESTADO_PAGO:
        type: string
      FECHA:
        type: string
      PK_ID_DOMICILIO:
        type: integer
        format: int64
      TELEFONO:
        type: string
  models.Ingrediente:
    title: Ingrediente
    type: object
    properties:
      ACTIVO:
        type: boolean
      CALORIAS:
        type: integer
        format: int64
      FOTO:
        type: string
      NOMBRE:
        type: string
      PESO:
        type: integer
        format: int64
      PK_ID_INGREDIENTE:
        type: integer
        format: int64
      PK_ID_INVENTARIO:
        type: integer
        format: int64
      TIPO:
        type: string
  models.Inventario:
    title: Inventario
    type: object
    properties:
      CANTIDAD:
        type: integer
        format: int64
      FECHA:
        type: string
      PK_ID_INGREDIENTE:
        type: integer
        format: int64
      PK_ID_INVENTARIO:
        type: integer
        format: int64
      UNIDAD:
        type: integer
        format: int64
      UNIDAD_MINIMA:
        type: integer
        format: int64
  models.ItemPedido:
    title: ItemPedido
    type: object
    properties:
      CANTIDAD:
        type: integer
        format: int64
      PK_ID_ITEM_PEDIDO:
        type: integer
        format: int64
      PK_ID_PEDIDO:
        type: integer
        format: int64
  models.MetodoPago:
    title: MetodoPago
    type: object
    properties:
      DETALLE:
        type: string
      PK_ID_METODO_PAGO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
      TIPO:
        type: string
  models.Nomina:
    title: Nomina
    type: object
    properties:
      ESTADO:
        type: string
      FECHA:
        type: string
      MONTO:
        type: integer
        format: int64
      PK_ID_NOMINA:
        type: integer
        format: int64
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
  models.Pago:
    title: Pago
    type: object
    properties:
      ESTADO:
        type: string
      FECHA:
        type: string
      HORA:
        type: string
      MONTO:
        type: integer
        format: int64
      PK_ID_METODO_PAGO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
  models.Pedido:
    title: Pedido
    type: object
    properties:
      DELIVERY:
        type: boolean
      ESTADO:
        type: string
      FECHA:
        type: string
      HORA:
        type: string
      PK_ID_DOMICILIO:
        type: integer
        format: int64
      PK_ID_ITEM_PEDIDO:
        type: integer
        format: int64
      PK_ID_PAGO:
        type: integer
        format: int64
      PK_ID_PEDIDO:
        type: integer
        format: int64
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
  models.PedidoCliente:
    title: PedidoCliente
    type: object
    properties:
      PK_DOCUMENTO_CLIENTE:
        type: integer
        format: int64
      PK_ID_PEDIDO_CLIENTE:
        type: integer
        format: int64
      PK_ID_RESTAURANTE:
        type: integer
        format: int64
  models.Plato:
    title: Plato
    type: object
    properties:
      ACTIVO:
        type: boolean
      CALORIAS:
        type: integer
        format: int64
      DESCRIPCION:
        type: string
      FOTO:
        type: string
      NOMBRE:
        type: string
      PERSONALIZADO:
        type: boolean
      PK_ID_ITEM_PEDIDO:
        type: integer
        format: int64
      PK_ID_PLATO:
        type: integer
        format: int64
      PRECIO:
        type: integer
        format: int64
  models.PlatoIngrediente:
    title: PlatoIngrediente
    type: object
    properties:
      CANTIDAD:
        type: integer
        format: int64
      PK_ID_INGREDIENTE:
        type: integer
        format: int64
      PK_ID_PLATO:
        type: integer
        format: int64
      PK_ID_PLATO_INGREDIENTE:
        type: integer
        format: int64
  models.Reserva:
    title: Reserva
    type: object
    properties:
      estado:
        type: string
      fecha:
        type: string
        format: datetime
      hora:
        type: string
      personas:
        type: integer
        format: int64
      pk_id_reserva:
        type: integer
        format: int64
      pk_id_restaurante:
        type: integer
        format: int64
  models.Restaurante:
    title: Restaurante
    type: object
    properties:
      dias_laborales:
        type: string
      hora_apertura:
        type: string
      nombre_restaurante:
        type: string
      pk_id_restaurante:
        type: integer
        format: int64
  models.Trabajador:
    title: Trabajador
    type: object
    properties:
      apellido:
        type: string
      fecha_ingreso:
        type: string
        format: datetime
      fecha_nacimiento:
        type: string
        format: datetime
      fecha_retiro:
        type: string
        format: datetime
      nombre:
        type: string
      nuevo:
        type: boolean
      pk_documento_trabajador:
        type: integer
        format: int64
      pk_id_restaurante:
        type: integer
        format: int64
      rol:
        type: string
      sueldo:
        type: integer
        format: int64
      telefono:
        type: string
  models.any:
    title: any
    type: object
  nil:
    title: nil
    type: object
