appname = el_fogon_de_maria
httpport = 8080
runmode = test

# Otras configuraciones
enabledocs = false
copyrequestbody = true
swagger = false

# Configuración de la base de datos de pruebas
db_host = localhost
db_port = 5432
db_user = postgres
db_pass = 12346
db_name = restaurante_test_db

# Firebase
firebase_project_id = el-fogon-de-maria

# VAPID (Web Push Notifications) - claves de prueba
vapid_public_key = BCFXrcyYwESaGDguqj1kidjzHw1QzAx47thsynar5jA2TdDF9fc9nXNCi11ugeAip_UNAFBzcqKt6GG157uK-Pg
vapid_private_key = 6ACdjLgL8qw8s2RGvnkRyARS56T0NSC4NxWCxeC69Ew
vapid_subject = mailto:test@restaurante.com
